version: "3.7"

services:
  postgres:
    image: postgres:alpine
    container_name: dev_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - services-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "ramonsantos.pe@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - services-network

networks:
  services-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
