default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  password: 1234
  username: postgres
  pool: 5

development:
  <<: *default
  database: finances_development

test:
  <<: *default
  database: finances_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 15
